<?php

namespace DGamesBundle\Entity;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestGames($limit = null)
    {
        $qp = $this->createQueryBuilder('g')->select('g')->addOrderBy('g.releasedate', 'DESC');

        if (false === is_null($limit))
            $qp->setMaxResults($limit);

        return $qp->getQuery()->getResult();
    }
}
